grails-app/controllers/grails/plugin/DataTablesController.groovy
package grails.plugin

import grails.converters.JSON
import grails.util.Holders
import org.springframework.context.ApplicationContext

class DataTablesController {
    def dataTablesService
    def grailsApplication

    /**
     * Get AJAX data for a table.
     * @return
     */
    def getData() {
        def time0 = System.currentTimeMillis()
        def tableDefinition = getTableDefinition(params.name)
        if(!tableDefinition) {
            def resultMap = [:]
            if(params.draw) {
                resultMap.draw = params.draw as int
            }
            resultMap.error = "Your session has expired."
            render resultMap as JSON
            return
        }
        def sortIndex = params."order[0][column]"
        if(null != sortIndex) {
            sortIndex = sortIndex as int
        }

        // Get the item data.
        def itemData = dataTablesService.getData(
                tableDefinition,
                params."search[value]",
                getColumnSearchParams(params, tableDefinition),
                sortIndex,
                params."order[0][dir]",
                params.length,
                params.start,
                params.dynamicSqlRestriction
        )

        // Loop through items and add them to the output.
        def data = []
        def columns = tableDefinition.getColumnsForTable()
        def itemIndex = params.start ?: 0
        for(item in itemData.items) {
            def rowArray = []
            columns.each { column ->
                rowArray << column.getTableFormattedValueFromItem(item, itemIndex)
            }
            data << rowArray
            itemIndex++
        }

        def resultMap = [:]
        if(params.draw) {
            resultMap.draw = params.draw as int
        }
        resultMap.recordsTotal = itemData.count ?: 0
        resultMap.recordsFiltered = itemData.filteredCount ?: 0
        resultMap.data = data
        render resultMap as JSON
        def time1 = System.currentTimeMillis()
        log.debug "DataTables controller delivered AJAX data in ${time1 - time0}ms."
    }

    /**
     * Download a report.
     */
    def getReport() {
        def tableDefinition = getTableDefinition(params.name)

        // Check that reporting is enabled for this table.
        if(!tableDefinition?.reportingEnabled) {
            response.status = 404
            return
        }

        def sortIndex = params.sortIndex
        if(null != sortIndex) {
            sortIndex = sortIndex as int
        }

        // Get the item data.
        def itemData = dataTablesService.getData(
                tableDefinition,
                params.search,
                getColumnSearchParams(params, tableDefinition),
                sortIndex,
                params.sortDir,
                0,
                0,
                params.dynamicSqlRestriction
        )

        // Find which service to use to generate report.
        def reportServiceName = grailsApplication.config.grails.plugin.datatables.reportService
        if(!reportServiceName) {
            reportServiceName = "dataTablesReportService"
        }
        ApplicationContext ctx = Holders.grailsApplication.mainContext
        def reportService =  ctx.getBean(reportServiceName);
        def reportData = reportService.formatReport(itemData.items, tableDefinition)

        // Send it off.
        response.setContentType(reportData.contentType)
        def fileName = g.message(code: "datatables.${tableDefinition.name}.reportFileName", default: reportData.defaultFileName)
        response.setHeader("Content-disposition", "attachment;filename=${fileName}")
        // Add cookie for the JQuery fileDownload plugin.
        def cookie = new javax.servlet.http.Cookie("fileDownload", "true")
        cookie.path = "/"
        cookie.maxAge = 100
        // Sometimes we get a broken pipe exception, presumably if the user cancels the download. It's not reproducable. Use try-catch block to resolve.
        try {
            response.addCookie(cookie)
            response.setHeader("Cache-Control", "no-store, no-cache") // This line makes IE8 and worse behave.
            reportService.writeReport(reportData, response.outputStream)
            response.outputStream.flush()
            response.outputStream.close()
        } catch(e) {
            log.debug "Error occurred while writing report to response: ${e}"
        }
    }

    /**
     * Gets a TableDefinition from the session.
     * @param params
     * @return
     */
    private def getTableDefinition(def name) {
        def tableDefinitions = session.tableDefinitions
        if(!tableDefinitions) {
            // Session must have expired or request is bogus.
            return null
        }
        tableDefinitions[name]
    }

    /**
     * Get column search parameters from params.
     * @param params
     * @param tableDefinition
     * @return a Map containing the column search parameters, using the columns as the keys.
     */
    private def getColumnSearchParams(def params, def tableDefinition) {
        def columnSearchParams = null
        if(tableDefinition.columnSearching) {
            columnSearchParams = [:]
            tableDefinition.getColumnsForTable().eachWithIndex { column, index ->
                if(column.searchable) {
                    def columnSearchParameter = params."columns[${index}][search][value]"
                    if(columnSearchParameter) {
                        columnSearchParams[column] = columnSearchParameter
                    }
                }
            }
        }
        columnSearchParams
    }
}

grails-app/views/dataTablesTemplates/_dataTableJavaScript.gsp
%{--Javascript Template for the DataTable.--}%
<asset:script type="text/javascript">

    %{--Write the table initialization script.--}%
    var ${name} = null;
    <g:if test="${tableDefinition.deferInitialization}">
        %{--This creates a function named initializeTableName (where TableName is the name of the table) that can be used to initialize the datatable--}%
        %{--sometime after the page is loaded.--}%
        function initialize${name[0].toUpperCase()}${name[1..-1]}() {
            <dt:writeInitializationScript attr="${attr}" tableDefinition="${tableDefinition}" dataTablesConfig="${dataTablesConfig}"/>
        }
    </g:if>

    %{--Beginning of document ready section.--}%
    $(function() {

        <g:if test="${!tableDefinition.deferInitialization}">
            <dt:writeInitializationScript attr="${attr}" tableDefinition="${tableDefinition}" dataTablesConfig="${dataTablesConfig}"/>
        </g:if>

        %{--Add Search and Reset buttons to DOM.--}%
        var searchDiv = $("#${name}Search");
        searchDiv.addClass("searchGroup");
        searchDiv.html(' \
        <g:if test="${tableDefinition.searchButton}"> \
            <input id="${name}SearchBox"/> \
            <span class="buttons"> \
                <button id="${name}SearchButton" class="datatablesButtons" type="button"> \
                    <g:message code="datatables.language.searchButton" default="Search"/> \
                </button> \
            </span class="buttons"> \
        </g:if> \
        <g:if test="${tableDefinition.resetButton}"> \
            <span class="buttons"> \
                <button id="${name}ResetButton" class="datatablesButtons" type="button"> \
                    <g:message code="datatables.language.resetButton" default="Reset"/> \
                </button> \
            </span class="buttons"> \
        </g:if> \
        ');

        %{--Add actions to Search and Reset buttons.--}%
        <g:if test="${tableDefinition.searchButton}">
            $("#${name}SearchBox").keypress(function(e){if(e.which == 13){${name}.search($("#${name}SearchBox").val()).draw();}});
            $("#${name}SearchButton").click(function(){${name}.search($("#${name}SearchBox").val()).draw();});
        </g:if>
        <g:if test="${tableDefinition.resetButton}">
            $("#${name}ResetButton").click(function() {
                <g:if test="${tableDefinition.searchButton}">
                    $("#${name}SearchBox").val("");
                </g:if>
                ${name}.search("").draw();
            });
        </g:if>

        %{--Restore state for column search input boxes.--}%
        <g:if test="${tableDefinition.columnSearching && tableDefinition.stateSave}">
            var state = ${name}.state.loaded();
            if(state) {
                ${name}.columns().eq(0).each(function(colIdx) {
                    var colSearch = state.columns[colIdx].search;
                    if(colSearch.search) {
                        $('input', ${name}.column(colIdx).footer()).val(colSearch.search);
                    }
                });
            }
        </g:if>

        %{--Add column searching function.--}%
        <g:if test="${tableDefinition.columnSearching}">
            ${name}.columns().every(function() {
                var that = this;
                $('input', this.footer()).on('keyup change', function() {
                    if(that.search() !== this.value) {
                        that.search(this.value).draw();
                    }
                });
            });

            %{--Adjust search box widths whenever column widths are adjusted.--}%
            ${name}.on('column-sizing.dt', function(e, settings) {
                adjust${name}ColumnSearchWidths();
            });
        </g:if>

        %{--Write the report URL function.--}%
        <g:if test="${tableDefinition.reportingEnabled}">
            function get${name}ReportUrl() {
                <g:if test="${tableDefinition.controller || tableDefinition.reportAction}">
                    var reportUrl = "<g:createLink controller="${tableDefinition.controller}" action="${tableDefinition.reportAction ?: "getReport"}" params="${tableDefinition.ajaxParams}"/>"
                </g:if><g:else>
                    var reportUrl = "<g:createLink controller="dataTables" action="getReport" params="${tableDefinition.ajaxParams}"/>"
                </g:else>

                var order = ${name}.order();
                <g:if test="${tableDefinition.columnSearching}">
                    var columnSearches = "";
                    ${name}.columns().every(function() {
                        columnSearches += '&columns[' + this.index() + '][search][value]=' + this.search();
                    });
                </g:if>
                return reportUrl + "&search=" + ${name}.search() + "&sortIndex=" + order[0][0] + "&sortDir=" + order[0][1] +
                    <g:if test="${tableDefinition.columnSearching}">
                            columnSearches +
                    </g:if>
                    <g:if test="${tableDefinition.sqlRestrictionFunction}">
                        "&dynamicSqlRestriction=" + ${tableDefinition.sqlRestrictionFunction}() +
                    </g:if>
                    "&report=${name}";
            }
        </g:if>

        %{--Write the script for the report button.--}%
        <g:if test="${tableDefinition.reportButton}">
            var reportDiv = $("#${name}Report");
            reportDiv.addClass("reportGroup");
            reportDiv.html(' \
                <button id="${name}ReportButton" class="datatablesButtons" type="button" title="${g.message(code: "datatables.language.downloadReport.title", default: "")}"> \
                    <g:message code="datatables.language.downloadReport.text" default="Download Report"/> \
                </button> \
            ');
            $("#${name}ReportButton").click(function(clickEvent){
                var numRecords = ${name}.page.info().recordsDisplay;
                <g:if test="${tableDefinition.reportFunction}">
                    ${tableDefinition.reportFunction}(clickEvent, numRecords, get${name}ReportUrl());
                </g:if><g:else>
                    %{--Stop the browser from following.--}%
                    clickEvent.preventDefault();
                    window.location.href = get${name}ReportUrl();
                </g:else>
            });
        </g:if>

        %{--If using jQueryUI, style the length dropdown. It's necessary to rewire the event from the jQueryUI selectmenu back to the original html one.--}%
        %{--Also, style the buttons.--}%
        <g:if test="${dataTablesConfig.jQueryUI}">
            var lengthSelect=$("#${name}_length select");
            lengthSelect.selectmenu({
                change:function() {
                    lengthSelect.change();
                }
            });
            $("button.datatablesButtons").button();
        </g:if>

        %{--If there is an error function, wire it up.--}%
        <g:if test="${tableDefinition.errorFunction}">
            $.fn.dataTable.ext.errMode = "none";
            ${name}.on("error.dt", ${tableDefinition.errorFunction});
        </g:if>

        %{--Write the select all function.--}%
        <g:if test="${tableDefinition.hasSelectAll}">
            $("#${name}_check_all").click(function () {
                $("input", ${name}.rows().nodes()).prop("checked", this.checked);
            });
        </g:if>

    %{--End of document ready section.--}%
    });

    %{--Write function for adjusting column search input widths.--}%
    <g:if test="${tableDefinition.columnSearching}">
        function adjust${name}ColumnSearchWidths() {
            $("table#${name} tfoot tr td input.columnSearch").each(function() {
                var parentWidth = $(this.parentNode).width();
                if(parentWidth > 4) {
                    $(this).width(parentWidth - 4);
                }
            });
        }
    </g:if>

    %{--Write function for adjusting column widths.--}%
    function adjust${name}ColumnWidths() {
        ${name}.columns.adjust();
    }

    %{--Render the custom functions template, if it exists and has not already been rendered on this page.--}%
    <g:if test="${dataTablesConfig.functionsTemplate && !pageScope.functionsTemplateRendered}">
        <g:render template="${dataTablesConfig.functionsTemplate}"
                  plugin="${dataTablesConfig.functionsTemplatePlugin}"
                  model="${[out: out, dataTablesConfig: dataTablesConfig, tableDefinition: tableDefinition, attr: attr]}"/>
    </g:if>

</asset:script>

grails-app/views/dataTablesTemplates/_drawCallbackFunction.gsp
function(settings) {
    <g:if test="${attr.drawCallback}">
        %{--Call drawCallback function provided in attributes.--}%
        (${attr.drawCallback})(settings);
    </g:if>
    var pageInfo = this.api().page.info();
    if(Math.ceil((pageInfo.recordsDisplay) / pageInfo.length) > 1)  {
        $("#${tableDefinition.name}_paginate.dataTables_paginate").css("display", "block");
    } else {
        $("#${tableDefinition.name}_paginate.dataTables_paginate").css("display", "none");
    }
    if(pageInfo.recordsDisplay > 10) {
        $("#${tableDefinition.name}_length.dataTables_length").css("display", "block");
    } else {
        $("#${tableDefinition.name}_length.dataTables_length").css("display", "none");
    }

    <g:if test="${!tableDefinition.hasLocalData}">
        if(${tableDefinition.name} != null) {
        %{--Execute the following only after the table has been initialized.--}%
    </g:if>

    %{--Select the correct heading according to the number of rows in the table.--}%
    var numRows = pageInfo.recordsTotal;
    $("#${tableDefinition.name}HeadingEmpty").toggle(0 == numRows);
    $("#${tableDefinition.name}HeadingSingular").toggle(1 == numRows);
    $("#${tableDefinition.name}HeadingPlural").toggle(1 < numRows);

    %{--Hide or show the table according to whether it contains any rows.--}%
    <g:if test="${tableDefinition.hideWhenEmpty}">
        $("#${tableDefinition.name}Container").toggle(0 < numRows);
    </g:if>

    %{--Write callback to clear select all checkbox.--}%
    <g:if test="${!tableDefinition.hasSelectAll}">
        $("#${tableDefinition.name}_check_all").attr("checked", false);
    </g:if>

    %{--Write callback to adjust column search widths.--}%
    <g:if test="${tableDefinition.columnSearching}">
        adjust${tableDefinition.name}ColumnSearchWidths();
    </g:if>

    %{--Update the Record Count container.--}%
    $(".${tableDefinition.name}Count").html(numRows);

    <g:if test="${!tableDefinition.hasLocalData}">
        }
    </g:if>
}

grails-app/views/dataTablesTemplates/_initCompleteFunction.gsp
function(settings, json) {
    <g:if test="${attr.initComplete}">
        %{--Call initComplete function provided in attributes.--}%
        (${attr.initComplete})(settings, json);
    </g:if>
    $("#${tableDefinition.name}HeadingLoading").toggle(false);
    var numRows = this.api().page.info().recordsTotal;
    $('.${tableDefinition.name}Count').html(numRows);
}

grails-app/views/dataTablesTemplates/_metadata.gsp
<g:set var="dataTablesService" bean="dataTablesService"/>
<div>
    <style type="text/css" scoped>
        table.metadatatable td {
            padding-left: 0px;
            padding-right: 10px;
        }
        div.datatablesMetadata {
            border: 3px #1a6699 solid;
            margin-bottom: 2px;
            border-radius: 10px;
            font-size: 11px;
            background: #9ce;
        }
        div.datatablesMetadata h3 {
            margin-top: 2px;
            margin-bottom: 2px;
            padding: 0;
        }
        div.datatablesMetadata h4 {
            margin-top: 2px;
            margin-bottom: 2px;
        }
        div.datatablesMetadataHeading {
            margin: 0;
            padding: 1px;
            text-align: center;
        }
        div.datatablesMetadataBody {
            background: white;
            padding: 5px;
            border-top: 3px #1a6699 solid;
            border-bottom: 3px #1a6699 solid;
        }
        div.datatablesMetadata h3 {
            margin: 0;
        }
        div.datatablesWatermark {
            position: absolute;
            left: 0;
            right: 0;
            margin-top: 800px;
            color: #1a6699;
            opacity: 0.15;
            font-size: 100px;
            font-weight: bold;
            z-index: 1000;
            transform: rotate(45deg);
            text-align: center;
        }
    </style>
    <div class="datatablesMetadata">
        <div class="datatablesMetadataHeading">
            <h3>DataTable Metadata for Table <i>${tableDefinition.name}</i></h3>
        </div>
        <div class="datatablesMetadataBody">
            <div class="datatablesWatermark">DataTable Metadata</div>
            %{--Configuration Settings--}%
            <h3>Configuration Options</h3>
            <table class="metadatatable">
                <g:each in="${["dateFormat", "dateTimeFormat", "timeFormat", "dbDateFormat", "dbDateTimeFormat", "dbTimeFormat", "dateFormatLength", "dateTimeFormatLength", "timeFormatLength"]}">
                    <tr><td><a href="https://bitbucket.org/ben-wilson/grailsdatatables/wiki/${it}">grails.plugin.datatables.${it}</a>:</td><td>${dataTablesService[it]}</td></tr>
                </g:each>
                <g:each in="${["functionsTemplate", "functionsTemplatePlugin", "jQueryUI", "reportService", "reportSizeLimit", "tableDefaults"]}">
                    <tr><td><a href="https://bitbucket.org/ben-wilson/grailsdatatables/wiki/${it}">grails.plugin.datatables.${it}</a>:</td><td>${dataTablesConfig[it]}</td></tr>
                </g:each>
            </table><br/>

            %{--Table Metadata--}%
            <h3>Table Options</h3>
            <table class="metadatatable">
                <g:each in="${["adjustColumnWidths", "ajaxParams", "columnSearching", "controller", "dataAction", "dataItems", "deferInitialization", "domainClass", "errorFunction", "headingParams", "hideWhenEmpty", "name", "reportAction", "reportButton", "reportFunction", "reportingEnabled", "resetButton", "searchButton", "searching", "serverDataLoad", "serverSide", "showMetadata", "sqlRestrictionFunction", "tableSearching"]}">
                    <tr><td><a href="https://bitbucket.org/ben-wilson/grailsdatatables/wiki/${it == "name" ? "tableName" : it}">${it}</a>:</td><td>${tableDefinition[it]}</td></tr>
                </g:each>
                <tr><td><a href='http://datatables.net/reference/option/ordering'>ordering</a>:</td><td>${(attr.ordering ?: "true") }</td></tr>
                <tr><td><a href='http://datatables.net/reference/option/info'>info</a>:</td><td>${(attr.info ?: "true")}</td></tr>
            </table><br/>

            %{--Table Messages--}%
            <h3>Table Messages</h3>
            <table class="metadatatable">
                <tr>
                    <td><h4>Description</h4></td>
                    <td><h4>messages.properties key</h4></td>
                    <td><h4>Value</h4></td>
                </tr>
                <tr><td>Empty Table Heading</td><td>datatables.${tableDefinition.name}.heading.empty</td><td><g:message code="datatables.${tableDefinition.name}.heading.empty" default=""/></td></tr>
                <tr><td>Singular Table Heading</td><td>datatables.${tableDefinition.name}.heading.singular</td><td><g:message code="datatables.${tableDefinition.name}.heading.singular" default=""/></td></tr>
                <tr><td>Plural Table Heading</td><td>datatables.${tableDefinition.name}.heading.plural</td><td><g:message code="datatables.${tableDefinition.name}.heading.plural" default=""/></td></tr>
                <g:each status="index" var="column" in="${tableDefinition.columns}">
                    <tr>
                        <td>Column ${index} Heading</td>
                        <td>
                            <g:if test="${column.headingKey}">${column.headingKey}</g:if>
                            <g:else>datatables.${tableDefinition.name}.${column.name}</g:else>
                        </td>
                        <td><g:message code="datatables.${tableDefinition.name}.${column.name}" default=""/></td>
                    </tr>
                </g:each>
                <tr><td>Report Filename</td><td>datatables.${tableDefinition.name}.reportFileName</td><td><g:message code="datatables.${tableDefinition.name}.reportFileName" default=""/></td></tr>
            </table><br/>

            %{--Table Messages--}%
            <h3>Language Messages</h3>
            <table class="metadatatable">
                <tr>
                    <td><h4>messages.properties key</h4></td>
                    <td><h4>Value</h4></td>
                </tr>
                <g:each in="${["emptyTable", "info", "infoEmpty", "infoFiltered", "infoPostFix", "thousands", "lengthMenu", "loadingRecords", "processing", "search", "zeroRecords", "paginate.first", "paginate.last", "paginate.next", "paginate.previous", "aria.sortAscending", "aria.sortDescending", "searchButton", "resetButton", "loading", "downloadReport.title", "downloadReport.text"]}">
                    <tr><td>datatables.language.${it} </td><td><g:message code="datatables.language.${it}" default=""/></td></tr>
                </g:each>
            </table><br/>

            %{--Columns--}%
            <h3>Table Columns</h3>
            <table class="metadatatable">
                <tr>
                    <td><h4>name:</h4></td>
                    <td><h4>heading</h4></td>
                    <td><h4>dataType</h4></td>
                    <td><h4>criteria</h4></td>
                    <td><h4>visible</h4></td>
                    <td><h4>include</h4></td>
                    <td><h4>searchable</h4></td>
                    <td><h4>orderable</h4></td>
                </tr>
                <g:each var="column" in="${tableDefinition.columns}">
                    <tr>
                        <td>${column.name}</td>
                        <td>${column.heading}</td>
                        <td>${column.dataType}</td>
                        <td>${column.criteria}</td>
                        <td>${column.visible}</td>
                        <td>${column.include ?: "all"}</td>
                        <td>${column.searchable}</td>
                        <td>${column.orderable}</td>
                    </tr>
                </g:each>
            </table><br/>

            %{--Column Display Details--}%
            <h3>Table Column Display Details</h3>
            <table class="metadatatable">
                <tr>
                    <td><h4>name:</h4></td>
                    <td><h4>dataFunction</h4></td>
                    <td><h4>link</h4></td>
                    <td><h4>linkIdField</h4></td>
                    <td><h4>trueText</h4></td>
                    <td><h4>falseText</h4></td>
                </tr>
                <g:each var="column" in="${tableDefinition.columns}">
                    <tr>
                        <td>${column.name}</td>
                        <td>${column.dataFunction ? "Yes" : ""}</td>
                        <td>${column.link}</td>
                        <td>${column.linkIdField}</td>
                        <td>${column.trueText}</td>
                        <td>${column.falseText}</td>
                    </tr>
                </g:each>
            </table>
        </div>
        <div class="datatablesMetadataHeading">
            <h3>DataTable Metadata for Table <i>${tableDefinition.name}</i></h3>
        </div>
    </div>
</div>